### PR TITLE
Improve some minor things in install script

### PR DESCRIPTION
**Pull request by vsund**
This PR improves some minor flaws as wording and comments, and also breaks repetitive functionality into dedicated functions.

Please note that this script still shouldn't run, as there isn't (yet) content on https://raw.githubusercontent.com/galaxypi/galaxy/master/seeds and there's no release for my architecture (`linux_x86_64`). I tested this with manually with changing those two things (to https://raw.githubusercontent.com/galaxypi/galaxy/develop/seeds and `linux_amd64`).

### CODE REVIEW

**Comment by faddat** [comment]
Thank you @vsund!

Let's talk today or tomorrow about the seeds file, and maybe some new binaries, too!

**Comment by vsund** [comment]
Sure 👍

**Comment by faddat** [comment]
I see you've gone all functional bash on this!  Nice!

**Comment by vsund** [comment]
As a small bonus: I just tested this with `sh` and worked so far. Seems like this script would run on every POSIX-compatible system :)

**Comment by guylepage3** [comment]
Thanks @vsund !

**Pull request merged**
